packages:
  - "packages/*"
  - "tools/*"
  - "samples/*"

catalog:
  "@asteasolutions/zod-to-openapi": "7.3.4"
  "@aws-sdk/client-cloudwatch": "3.840.0"
  "@aws-sdk/client-dynamodb": "3.840.0"
  "@aws-sdk/client-eventbridge": "3.840.0"
  "@aws-sdk/client-sfn": "3.840.0"
  "@aws-sdk/lib-dynamodb": "3.840.0"
  "@aws-sdk/types": "3.840.0"
  "@effect-ts/core": "0.60.5"
  "@release-it/conventional-changelog": "10.0.1"
  "@release-it-plugins/workspaces": "5.0.3"
  "release-it": "19.0.3"
  "@commitlint/cli": "19.8.1"
  "@commitlint/config-conventional": "19.8.1"
  "@effect/platform": "0.87.1"
  "@effect/platform-node": "0.88.3"
  "@eslint/js": "9.30.0"
  "@fastify/sensible": "6.0.3"
  "@middy/core": "6.3.2"
  "@middy/do-not-wait-for-empty-event-loop": "6.3.1"
  "@nats-io/transport-node": "3.0.2"
  "@nats-io/nats-core": "3.0.2"
  "@nats-io/services": "3.0.2"
  "@opentelemetry/api": "1.9.0"
  "@opentelemetry/api-logs": "0.202.0"
  "@opentelemetry/exporter-logs-otlp-http": "0.202.0"
  "@opentelemetry/instrumentation": "0.202.0"
  "@opentelemetry/sdk-logs": "0.202.0"
  "@opentelemetry/sdk-node": "0.202.0"
  "@scalar/fastify-api-reference": "1.32.1"
  "@tsconfig/node22": "22.0.2"
  "@types/aws-lambda": "8.10.150"
  "@types/http-errors": "2.0.5"
  "@types/lodash": "4.17.19"
  "@types/luxon": "3.6.2"
  "@types/node": "24.0.8"
  "@typescript-eslint/eslint-plugin": "8.35.1"
  "@typescript-eslint/parser": "8.35.1"
  "@vitest/coverage-v8": "3.2.4"
  "@vitest/ui": "3.2.4"
  "ajv": "8.17.1"
  "async-mutex": "0.5.0"
  "aws-lambda": "1.0.7"
  "change-case": "5.4.4"
  "cockatiel": "3.2.1"
  "commander": "14.0.0"
  "effect": "3.16.10"
  "eslint": "9.30.0"
  "eslint-config-prettier": "10.1.5"
  "fastify": "5.4.0"
  "globals": "16.2.0"
  "http-errors": "2.0.0"
  "lodash": "4.17.21"
  "luxon": "3.6.1"
  "nanoid": "5.1.5"
  "openapi3-ts": "4.5.0"
  "prettier": "3.6.2"
  "rimraf": "6.0.1"
  "senselogs": "1.0.7"
  "testcontainers": "11.0.3"
  "ts-node": "10.9.2"
  "ts-pattern": "5.7.1"
  "turbo": "2.5.4"
  "typescript": "5.8.3"
  "ulid": "3.0.1"
  "vitest": "3.2.4"
  "yaml": "2.8.0"
  "zod": "3.25.67"
  "zod-to-json-schema": "3.24.6"
