packages:
  - packages/*
  - tools/*
catalog:
  "@asteasolutions/zod-to-openapi": ^7.3.2
  "@aws-sdk/client-cloudwatch": ^3.821.0
  "@aws-sdk/client-dynamodb": ^3.821.0
  "@aws-sdk/client-eventbridge": ^3.821.0
  "@aws-sdk/client-sfn": ^3.821.0
  "@aws-sdk/lib-dynamodb": ^3.821.0
  "@aws-sdk/types": ^3.821.0
  "@aws-sdk/service-error-classification": ^3.374.0
  "@changesets/cli": ^2.29.4
  "@effect-ts/core": ^0.60.5
  "@effect/platform": ^0.63.0
  "@effect/platform-node": ^0.58.0
  "@eslint/js": ^9.28.0
  "@fastify/sensible": ^6.0.3
  "@middy/core": ^6.0.0
  "@middy/do-not-wait-for-empty-event-loop": ^6.0.0
  "@scalar/fastify-api-reference": ^1.31.2
  "@swc/cli": ^0.7.7
  "@swc/core": ^1.11.29
  "@swc/jest": ^0.2.29
  "@tsconfig/node22": ^22.0.2
  "@types/aws-lambda": ^8.10.137
  "@types/http-errors": ^2.0.4
  "@types/jest": ^29.5.14
  "@types/lodash": ^4.17.17
  "@types/luxon": ^3.3.0
  "@types/node": ^22.15.29
  "@typescript-eslint/eslint-plugin": ^8.33.0
  "@typescript-eslint/parser": ^8.33.0
  aws-lambda: ^1.0.7
  change-case: ^4.1.2
  commander: ^14.0.0
  effect: ^3.10.0
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  fastify: ^5.3.3
  http-errors: ^2.0.0
  jest: ^29.7.0
  lodash: ^4.17.21
  luxon: ^3.3.0
  nanoid: ^3.3.6
  openapi3-ts: ^4.1.2
  prettier: ^3.5.3
  rimraf: ^6.0.1
  senselogs: ^1.0.5
  testcontainers: ^11.0.0
  ts-node: ^10.9.2
  ts-pattern: ^5.7.1
  tsx: ^4.19.4
  turbo: ^2.5.4
  typescript: ^5.8.3
  ulid: ^3.0.0
  yaml: ^2.3.4
  zod: ^3.21.4
  zod-to-json-schema: ^3.21.4
